Skeleton: 1000
Spider: 1000
Creeper: 1000
Zombie: 1000
IronGolem: 1000
Blaze: 1000
Witch: 1000
SkeletonEgg: 50
SpiderEgg: 50
CreeperEgg: 50
ZombieEgg: 50
IronGolemEgg: 50
BlazeEgg: 50
WitchEgg: 50