name: SpawnerShops
version: 1.2.1
main: me.noeffort.spawnershops.Main
author: NoEffort, Sonam
depend: [Vault]
commands:
    spawnershops:
        usage: /<command>
        aliases: [ss, spawner]
        description: Purchase Spawners! (Selling Coming Soon)
    reloadshop:
        usage: /<command>
        aliases: [rs, shopreload, ssreload]
        description: Reload SpawnerShops.
        
permissions:
    ss.use:
        default: true
        description: Grants the ability to use SpawnerShops!
    ss.admin:
        default: op
        description: Grants the ability to access Admin Commands in SpawnerShops!
